//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReaderRaport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReaderRaport.Resources.PageText", typeof(PageText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To na prawdę proste!.
        /// </summary>
        public static string idxHowDesc {
            get {
                return ResourceManager.GetString("idxHowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na początku stworzysz swoją pustą, wirtualną biblioteczkę..
        /// </summary>
        public static string idxHowList1 {
            get {
                return ResourceManager.GetString("idxHowList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Będziesz mógł ją pobrać i edytować nawet z tropikalnej wyspy bez dostępu internetu!.
        /// </summary>
        public static string idxHowList2 {
            get {
                return ResourceManager.GetString("idxHowList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gdy tylko będziesz chciał wyświetlić swoje statystyki, wrócisz tu ze swoimy cennymi danymi..
        /// </summary>
        public static string idxHowList3 {
            get {
                return ResourceManager.GetString("idxHowList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak to działa.
        /// </summary>
        public static string idxHowTitle {
            get {
                return ResourceManager.GetString("idxHowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie martw się, każdy poradzi sobie z obsługą biblioteczki :)        ///&lt;/br&gt; Zapiszemy ją do pliku .csv, który otworzysz w dowolnym arkuszu kalkulacyjnym jak Excel, LibreOffice czy OpenOffice. To tylko tabelka!.
        /// </summary>
        public static string idxLibraryDesc {
            get {
                return ResourceManager.GetString("idxLibraryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biblioteczka.
        /// </summary>
        public static string idxLibraryTitle {
            get {
                return ResourceManager.GetString("idxLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czasami przychodzi moment, że zastanawiasz się co najczęściej czytasz, w jakich miesiącach, czy wakacje dobrze wpływają na twoj nawyki czytelnicze, a gdzie wpływ miały postanowienia noworoczne.         ///Oto wlaśnie moment, by to sprawdzić!.
        /// </summary>
        public static string idxMotivationDesc {
            get {
                return ResourceManager.GetString("idxMotivationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motywacja.
        /// </summary>
        public static string idxMotivationTitle {
            get {
                return ResourceManager.GetString("idxMotivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaczynamy.
        /// </summary>
        public static string idxSummaryButton {
            get {
                return ResourceManager.GetString("idxSummaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz swoją bibioteczkę.
        /// </summary>
        public static string idxSummaryList1 {
            get {
                return ResourceManager.GetString("idxSummaryList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzupełnij ją w aplikacji lub pobierz i dodaj dane bezpośrednio na twoim komputerze.
        /// </summary>
        public static string idxSummaryList2 {
            get {
                return ResourceManager.GetString("idxSummaryList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz &lt;span class=&quot;badge badge-pill badge-primary&quot;&gt;Generuj raport &lt;/span&gt; w głównym menu!.
        /// </summary>
        public static string idxSummaryList3 {
            get {
                return ResourceManager.GetString("idxSummaryList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co teraz?.
        /// </summary>
        public static string idxSummaryTitle {
            get {
                return ResourceManager.GetString("idxSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj! W tej prostej aplikacji poznasz niektóre ze statytyk opisujących twoje nawyki czytelnicze. Naprzód!.
        /// </summary>
        public static string idxWelcomeDesc {
            get {
                return ResourceManager.GetString("idxWelcomeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Raport.
        /// </summary>
        public static string idxWelcomeTitle {
            get {
                return ResourceManager.GetString("idxWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Och nie, coś poszło źle. Na pewno twój plik ma dobry format?.
        /// </summary>
        public static string msgCSV {
            get {
                return ResourceManager.GetString("msgCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! Upewnij się, że twoja biblioteczka wygląda tak, jak się spodzewamy. Zajrzyj do sekcji pomocy w menu na górze..
        /// </summary>
        public static string msgCSVFormat {
            get {
                return ResourceManager.GetString("msgCSVFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super, plik wgrany! Wszystko idzie zgodnie z planem..
        /// </summary>
        public static string msgCSVSuccses {
            get {
                return ResourceManager.GetString("msgCSVSuccses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj raport.
        /// </summary>
        public static string navGenerateRaport {
            get {
                return ResourceManager.GetString("navGenerateRaport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch language.
        /// </summary>
        public static string navLanguage {
            get {
                return ResourceManager.GetString("navLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja elektroniczna biblioteczka.
        /// </summary>
        public static string navYourDigitalLibrary {
            get {
                return ResourceManager.GetString("navYourDigitalLibrary", resourceCulture);
            }
        }
    }
}
